In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df

location           district  \
0     город Ташкент, Юнусабадский район, Юнусабад 8-...       Юнусабадский   
1     город Ташкент, Яккасарайский район, 1-й тупик ...      Яккасарайский   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...       Чиланзарский   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...       Чиланзарский   
4     город Ташкент, Чиланзарский район, площадь Актепа       Чиланзарский   
...                                                 ...                ...   
7560  город Ташкент, Яшнободский район, Городок Авиа...        Яшнободский   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        Яшнободский   
7562  город Ташкент, Шайхантахурский район, Зульфиях...    Шайхантахурский   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...  Мирзо-Улугбекский   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...       Чиланзарский   

      rooms size  level  max_levels  price  
0         3   57      4           4  52000  
1         2   52      4           5  56000  
2         2   42      4           4  37000  
3         3   65      1           4  49500  
4         3   70      3           5  55000  
...     ...  ...    ...         ...    ...  
7560      1   38      5           5  24500  
7561      2   49      1           4  32000  
7562      2   64      3           9  40000  
7563      1   18      1           4  11000  
7564      1   30      2           4  22914  

[7565 rows x 7 columns]

In [2]:
import numpy as np
df['price'].replace('Договорная',np.nan,inplace=True)
df['size'].replace('Площадьземли:1сот',100,inplace=True)
df['price']=df['price'].astype(float)
df['size']=df['size'].astype(float)


C:\Users\user\AppData\Local\Temp\ipykernel_19860\2976548401.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['price'].replace('Договорная',np.nan,inplace=True)
C:\Users\user\AppData\Local\Temp\ipykernel_19860\2976548401.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For 

In [3]:
# NAN QIYMATLARNI ALOHIDA AJRATIB OLIB DATAFRAMEDAN O'CHIRIB TASHLADIK KEYIN ISHLATAMIZ
df_missing_price = df[df['price'].isna()]
df = df.dropna(subset=['price'])
df = df[df['price'] < 10_000_000]
df = df[df['price'] >= 1000]
df = df.drop(columns=['location'])


In [4]:






df.describe()

rooms          size        level   max_levels         price
count  7463.000000   7463.000000  7463.000000  7463.000000  7.463000e+03
mean      2.622136    113.549087     3.693957     6.024119  6.231773e+04
std       1.083268   1501.358913     2.236997     2.607323  1.306154e+05
min       1.000000      1.000000     1.000000     1.000000  1.000000e+03
25%       2.000000     50.000000     2.000000     4.000000  3.500000e+04
50%       3.000000     65.000000     3.000000     5.000000  4.650000e+04
75%       3.000000     85.000000     5.000000     9.000000  6.700000e+04
max      10.000000  70000.000000    19.000000    25.000000  6.630000e+06

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit

In [6]:
strafied_splits=StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)

In [7]:
for train_ix,test_ix in strafied_splits.split(df,df['district']):
    strat_train_set=df.iloc[train_ix]
    strat_test_set=df.iloc[test_ix]

In [8]:
strat_train_set

district  rooms   size  level  max_levels    price
665         Учтепинский      3   70.0      3           5  59000.0
3680       Юнусабадский      1   36.0      3           4  20500.0
7321        Яшнободский      5   92.0      7           9  62000.0
4710  Мирзо-Улугбекский      5  150.0      1           2  97000.0
1235       Чиланзарский      2   52.0      1           4  39500.0
...                 ...    ...    ...    ...         ...      ...
2248  Мирзо-Улугбекский      2   55.0      5           5  33000.0
4291        Яшнободский      1   28.0      1           3  19000.0
116        Юнусабадский      2   70.0      4           9  60000.0
1965  Мирзо-Улугбекский      3   85.0      4           4  84000.0
4439       Чиланзарский      1   25.0      3           9  21500.0

[5970 rows x 6 columns]

In [9]:
strat_test_set

district  rooms   size  level  max_levels    price
5871        Яшнободский      3  75.41     10          10  35000.0
7376  Мирзо-Улугбекский      1  35.00      3           4  26000.0
2900        Мирабадский      2  45.00      2           9  37000.0
6292       Чиланзарский      2  50.00      2           4  40000.0
52         Чиланзарский      2  45.00      2           4  48000.0
...                 ...    ...    ...    ...         ...      ...
317   Мирзо-Улугбекский      3  68.00      4           4  24000.0
1612       Чиланзарский      3  63.00      3           4  42000.0
2296        Мирабадский      3  80.00      3           5  72000.0
1749  Мирзо-Улугбекский      2  65.00      4           4  33000.0
3266  Мирзо-Улугбекский      3  78.00      3           5  52000.0

[1493 rows x 6 columns]

In [10]:
X=strat_train_set.drop('price',axis=1)
y=strat_train_set['price'].copy()

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
cat_encoder=OneHotEncoder()

X_cat=X[['district']]
X_cat_1hot=cat_encoder.fit_transform(X_cat)

In [13]:
X_cat_1hot.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
X_cat_1hot.toarray()[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [15]:






from sklearn.base import BaseEstimator,TransformerMixin

In [16]:
room_ix,size_ix=1,2
class CombineAttributeAdder(BaseEstimator,TransformerMixin):
    def fit(self,X,y=None):
        return self
    def transform(self,X):
        size_per_room=X.iloc[:,size_ix]/X.iloc[:,room_ix]
        return np.c_[X,size_per_room]

In [17]:
X.values[0,:]

array(['Учтепинский', 3, 70.0, 3, 5], dtype=object)

In [18]:
# att_adder=CombineAttributeAdder()
# X_extra_attribs=att_adder.transform(X.values)
# X_extra_attribs[0,:]

In [19]:
X.describe()

rooms          size        level   max_levels
count  5970.000000   5970.000000  5970.000000  5970.000000
mean      2.609548    110.972950     3.699162     6.044724
std       1.090237   1434.860862     2.221587     2.601888
min       1.000000      1.000000     1.000000     1.000000
25%       2.000000     50.000000     2.000000     4.000000
50%       2.000000     65.000000     3.000000     5.000000
75%       3.000000     85.000000     5.000000     9.000000
max      10.000000  70000.000000    19.000000    25.000000

In [20]:
X_num=X.drop('district',axis=1)




# STANDARTSCALER

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
# standart_scaler=StandardScaler()

# standart_scaler.fit(X_num)
# standart_scaler.transform(X_num)

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [24]:
num_pipeline=Pipeline([
    ('attribs_adder',CombineAttributeAdder()),
    ('std_scaler',StandardScaler())
])


In [25]:
num_attribs=list(X_num)
cat_attribs=['district']
full_pipeline=ColumnTransformer([
    ('num',num_pipeline,num_attribs),
    ('cat',OneHotEncoder(),cat_attribs)])

In [26]:
X_prepared=full_pipeline.fit_transform(X)
X_prepared[:10]

array([[ 0.35816515, -0.02855774, -0.31473943, -0.40155886, -0.18254696,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [-1.47645169, -0.0522554 , -0.31473943, -0.78592737,  0.26580677,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 2.19278199, -0.01322396,  1.48592601,  1.13591517,  0.18553884,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ],
       [ 2.19278199,  0.02720147, -1.21507214, -1.55466438, -0.58342794,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        

In [27]:
from sklearn.linear_model import LinearRegression

In [28]:
LR_model=LinearRegression()
LR_model.fit(X_prepared,y)

LinearRegression()

In [29]:
test_data=X.sample(10)
test_label=y.loc[test_data.index]

In [30]:
test_data_prepared=full_pipeline.transform(test_data)

In [31]:
predicted_labels=LR_model.predict(test_data_prepared)

In [32]:
pd.DataFrame({'bash':predicted_labels,'asl':test_label})

bash      asl
7020  42787.042051  36500.0
6504  37289.276056  30500.0
475   67801.547784  55000.0
1142  77521.866227  54000.0
5895  47207.375484  48000.0
5141  55263.614552  57000.0
1552  73660.017126  45500.0
3383  68642.630664  45800.0
4858  10516.344837  27000.0
6361  -2114.066824  25000.0

In [33]:
from sklearn.metrics import mean_absolute_error

mae=mean_absolute_error(test_label,predicted_labels)

In [34]:
print('MAE_LR=',mae)

MAE_LR= 14652.911185936126


In [35]:
from sklearn.metrics import mean_squared_error,r2_score
mse=mean_squared_error(test_label,predicted_labels)
print('RMSE_LR=',np.sqrt(mse))
r2 = r2_score(test_label,predicted_labels)
print("R^2 Score:", r2)

RMSE_LR= 17686.37362245637
R^2 Score: -1.4527386158926938


In [36]:







from sklearn.ensemble import RandomForestRegressor

In [37]:
RF_model=RandomForestRegressor()
RF_model.fit(X_prepared,y)

RandomForestRegressor()

In [38]:
y_predicted=RF_model.predict(test_data_prepared)

In [39]:
mse=mean_squared_error(test_label,y_predicted)
print('RMSE_RF=',np.sqrt(mse))
r2 = r2_score(test_label,predicted_labels)
print("R^2 Score:", r2)

RMSE_RF= 1577.2836183400946
R^2 Score: -1.4527386158926938


In [40]:
from xgboost import XGBRegressor
model = XGBRegressor(n_estimators=200, learning_rate=0.1, max_depth=7)
model.fit(X_prepared, y)


XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=7,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, ...)

In [41]:
y_predicted=model.predict(test_data_prepared)
mse=mean_squared_error(test_label,y_predicted)
print('RMSE_XGBR=',np.sqrt(mse))
r2 = r2_score(test_label,predicted_labels)
print("R^2 Score:", r2)

RMSE_XGBR= 3054.3816872315783
R^2 Score: -1.4527386158926938
