In [1]:
import numpy as np
names=np.array(['hasan','komil','javohir','husan','elyor','muhammadali','hasan'])
names

array(['hasan', 'komil', 'javohir', 'husan', 'elyor', 'muhammadali',
       'hasan'], dtype='<U11')

In [2]:
data = np .random.randn(7,4)
data

array([[ 1.08771743,  1.08155312, -1.61560326, -0.61476239],
       [ 0.65411723,  0.92608042, -0.93182328, -0.81340915],
       [-0.52102652, -0.25358865, -0.3770638 , -1.56533021],
       [ 1.57537751,  0.63906506, -1.68301174, -0.98992353],
       [ 0.25750341,  1.80965853, -0.47461839,  1.34576825],
       [ 1.47027217, -1.28359613, -0.43482557, -1.68588444],
       [-0.5467391 , -2.07530119,  0.46394804, -0.06810673]])

In [3]:
names=='hasan'

array([ True, False, False, False, False, False,  True])

In [4]:
data[names=='hasan']

array([[ 1.08771743,  1.08155312, -1.61560326, -0.61476239],
       [-0.5467391 , -2.07530119,  0.46394804, -0.06810673]])

In [5]:
data[names=='hasan',1]

array([ 1.08155312, -2.07530119])

In [6]:
data[names=='hasan',2:]

array([[-1.61560326, -0.61476239],
       [ 0.46394804, -0.06810673]])

In [7]:
print(names)
print(data)

['hasan' 'komil' 'javohir' 'husan' 'elyor' 'muhammadali' 'hasan']
[[ 1.08771743  1.08155312 -1.61560326 -0.61476239]
 [ 0.65411723  0.92608042 -0.93182328 -0.81340915]
 [-0.52102652 -0.25358865 -0.3770638  -1.56533021]
 [ 1.57537751  0.63906506 -1.68301174 -0.98992353]
 [ 0.25750341  1.80965853 -0.47461839  1.34576825]
 [ 1.47027217 -1.28359613 -0.43482557 -1.68588444]
 [-0.5467391  -2.07530119  0.46394804 -0.06810673]]


In [8]:
data[(names=='hasan')|(names=='husan')]

array([[ 1.08771743,  1.08155312, -1.61560326, -0.61476239],
       [ 1.57537751,  0.63906506, -1.68301174, -0.98992353],
       [-0.5467391 , -2.07530119,  0.46394804, -0.06810673]])

In [9]:
data[data<0]=0

In [10]:
data

array([[1.08771743, 1.08155312, 0.        , 0.        ],
       [0.65411723, 0.92608042, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [1.57537751, 0.63906506, 0.        , 0.        ],
       [0.25750341, 1.80965853, 0.        , 1.34576825],
       [1.47027217, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.46394804, 0.        ]])

In [11]:

array = np.arange(0, 9, 1).reshape(3, 3)

In [12]:
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
a=np.array([[[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8]],[[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],[[18, 19, 20],[21, 22, 23],[24, 25, 26]]])
arr6=a[0]
arr6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
a[1][1:,:2]

array([[12, 13],
       [15, 16]])

In [15]:
ism= np.array(['Hasan', 'Husan', 'Javohir', 'Elyor', 'Hasan', 'Javohir', 'Elyor'])
data=np.array( [[5, 6, 1, 1],
   [9, 1, 1, 1],
   [7, 7, 4, 2],
   [1, 5, 1, 9],
   [9, 9, 4, 5],
   [7, 5, 9, 6],
   [5, 3, 7, 4]])
data[ism=='Javohir'| ism=='Elyor']

TypeError: ufunc 'bitwise_or' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''