In [1]:
import numpy as np


In [9]:
arr=np.array([[np.zeros(shape=(2,4))],[np.arange(8).reshape(2,4)]])


In [10]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 1., 2., 3.],
         [4., 5., 6., 7.]]]])

In [11]:
np.random.randint(8,size=(2,4))

array([[3, 2, 5, 0],
       [0, 0, 5, 7]], dtype=int32)

In [12]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.arange(8).reshape(2,4),np.ones((2,4))

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]))