In [ ]:
# Numpy where funksiyasi ishlashi ko'rsatilgan 
# Where funksuya ishlashi bu yerda ikkta arra berilgan va faunksiya ichidagi shar qanoatlantirilsa 1-array
#  elementi aks holda 2-array elementi oini yangi array hosil qilinyapti
# yoki ikkinchi holatda arrayning har bir elementi 0da kattaligi tekshirilyapti 
# katta bo'lsa 10 kichik bo'lsa -10 ga almatirilyapti
import numpy as np

In [6]:
x_arr=np.array([1.1,1.2,1.3,1.4,1.5])
y_arr=np.array([2.1,2.2,2.3,2.4,2.5])

In [8]:
result=np.where(np.array([True,False,True,True,False]),x_arr,y_arr)

In [10]:
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [12]:
cond=np.array([True,False,True,True,False])

In [14]:
cond

array([ True, False,  True,  True, False])

In [16]:
result1=np.where(cond,x_arr,y_arr)
result1

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [18]:
arr=np.random.randn(4,4)

In [20]:
arr

array([[-1.80164911, -1.46205722, -0.377142  , -0.07088964],
       [ 0.96725164, -0.74039062,  0.51532444, -0.25432729],
       [ 0.84054741, -1.59227946, -0.85178825, -1.05275493],
       [-1.15113427, -0.32609539,  1.7023821 , -0.94406416]])

In [22]:
result2=np.where(arr<0,-10,10)
result2

array([[-10, -10, -10, -10],
       [ 10, -10,  10, -10],
       [ 10, -10, -10, -10],
       [-10, -10,  10, -10]])

In [30]:
result2=np.where(np.random.randn(6,8),-10,10)
result2

array([[-10, -10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10, -10, -10, -10]])