In [2]:
import numpy
a=numpy.arange(6)


In [4]:
a.T

array([0, 1, 2, 3, 4, 5])

In [33]:
a.reshape(3,2).T

array([[0, 2, 4],
       [1, 3, 5]])

In [35]:
a.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [31]:
a.reshape(1,6).T

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [39]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [41]:
a

array([0, 1, 2, 3, 4, 5])

In [94]:
b=numpy.arange(270).reshape(3,3,3,10).swapaxes(1,0)

In [96]:
b

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29]],

        [[ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
         [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119]],

        [[180, 181, 182, 183, 184, 185, 186, 187, 188, 189],
         [190, 191, 192, 193, 194, 195, 196, 197, 198, 199],
         [200, 201, 202, 203, 204, 205, 206, 207, 208, 209]]],


       [[[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59]],

        [[120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

        [[210, 211, 212, 213, 214, 215, 216, 217, 218, 219],
         [22

In [80]:
c=numpy.arange(12).reshape(3,4)

In [82]:
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
c.swapaxes(1,0)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])