In [ ]:
import numpy as np

arr1=numpy.random.randn(6)
arr1

array([ 0.2341732 , -0.75342496, -0.8068238 ,  0.51088662,  0.70277672,
        1.39229144])

In [17]:
qoldiq,butun=numpy.modf(arr1)

In [18]:
butun

array([ 0., -0., -0.,  0.,  0.,  1.])

In [19]:
qoldiq

array([ 0.2341732 , -0.75342496, -0.8068238 ,  0.51088662,  0.70277672,
        0.39229144])

In [20]:
numpy.modf(arr1)

(array([ 0.2341732 , -0.75342496, -0.8068238 ,  0.51088662,  0.70277672,
         0.39229144]),
 array([ 0., -0., -0.,  0.,  0.,  1.]))

In [22]:
np.sign(arr1)

array([ 1., -1., -1.,  1.,  1.,  1.])

In [23]:
# 2 ta massivni yaratib olamiz
arr2 = np.random.randn(6)
arr3 = np.random.randn(6)

In [24]:
arr2*arr3

array([ 1.06146738,  0.45897228,  0.06864293,  0.13106173, -0.29537293,
       -0.02213686])

In [26]:
arr2

array([ 0.8623706 , -0.35266291,  0.10514317, -0.376872  , -0.91983941,
       -1.64211372])

In [27]:
arr3

array([ 1.23087149, -1.30144755,  0.65285199, -0.34776191,  0.32111359,
        0.01348071])

In [28]:
np.multiply(arr2,arr3)

array([ 1.06146738,  0.45897228,  0.06864293,  0.13106173, -0.29537293,
       -0.02213686])